### PR TITLE
Added support for multiple entries in a single page

### PR DESCRIPTION
**Pull request by tonix-tuft**
Allows using multiple entries in a single page when using `encore_entry_link_tags` and `encore_entry_script_tags`:

```
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use function BenTools\WebpackEncoreResolver\encore_entry_link_tags;
use function BenTools\WebpackEncoreResolver\encore_entry_script_tags;
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php encore_entry_link_tags('main');?>
    <?php encore_entry_link_tags('specific');?>
    <?php encore_entry_script_tags('main');?>
    <?php encore_entry_script_tags('specific');?>
    <!-- ... -->
```

### CODE REVIEW

**Comment by tonix-tuft** [comment]
What's wrong with the `continuous-integration/travis-ci/pr` pipeline?

**Comment by bpolaszek** [comment]
Hello there,

Using multiple entries for a single page is actually working without this, what issue did you get?

**Comment by tonix-tuft** [comment]
In our case given the following Webpack Encore config:

```js
var Encore = require("@symfony/webpack-encore");
// var dotenv = require("dotenv");

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || "dev");
}

Encore
    // directory where compiled assets will be stored
    .setOutputPath("build/")
    // public path used by the web server to access the output path
    .setPublicPath("/build")
    // only needed for CDN's or sub-directory deploy
    //.setManifestKeyPrefix('build/')

    /*
     * ENTRY CONFIG
     *
     * Add 1 entry for each "page" of your app
     * (including one that's included on every page - e.g. "app")
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if your JavaScript imports CSS.
     */
    .addEntry("app", "./src/app.js")
    .addEntry("ticketing", "./src/components/ticketing/ticketing.js")

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()

    // will require an extra script tag for runtime.js
    // but, you probably want this, unless you're building a single-page app
    .enableSingleRuntimeChunk()

// ...
```

Encore generated the following `entrypoints.json`:

```json
{
  "entrypoints": {
    "app": {
      "js": [
        "/build/runtime.js",
        "/build/vendors~app~ticketing.js",
        "/build/vendors~app.js",
        "/build/app~ticketing.js",
        "/build/app.js"
      ],
      "css": [
        "/build/vendors~app~ticketing.css",
        "/build/vendors~app.css",
        "/build/app~ticketing.css",
        "/build/app.css"
      ]
    },
    "ticketing": {
      "js": [
        "/build/runtime.js",
        "/build/vendors~app~ticketing.js",
        "/build/vendors~ticketing.js",
        "/build/app~ticketing.js",
        "/build/ticketing.js"
      ],
      "css": [
        "/build/vendors~app~ticketing.css",
        "/build/app~ticketing.css",
        "/build/ticketing.css"
      ]
    }
  }
}
```

And when using `webpack-encore-resolver` as it is now:

```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use function BenTools\WebpackEncoreResolver\encore_entry_link_tags;
use function BenTools\WebpackEncoreResolver\encore_entry_script_tags;
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php encore_entry_link_tags('app');?>
    <?php encore_entry_link_tags('ticketing');?>
    <!-- ... -->
```

Results with:

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- app: -->
    <script src="/build/runtime.js"></script>
    <script src="/build/vendors~app~ticketing.js"></script>
    <script src="/build/vendors~app.js"></script>
    <script src="/build/app~ticketing.js"></script>
    <script src="/build/app.js"></script>

    <!-- ticketing: -->    
    <script src="/build/runtime.js"></script>
    <script src="/build/vendors~app~ticketing.js"></script>
    <script src="/build/vendors~ticketing.js"></script>
    <script src="/build/app~ticketing.js"></script>
    <script src="/build/ticketing.js"></script>
```

`"/build/runtime.js"` being included twice in the page (one for `app` and for `ticketing`), which breaks the page.
Also, `vendors~app~ticketing.js` as well as `/build/app~ticketing.js` are duplicated because they share code between the various modules, but we really need to include them only once in the page.

That's why I sent this PR, it fixes this behaviour and assures that the expected outcome is:

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- app: -->
    <script src="/build/runtime.js"></script>
    <script src="/build/vendors~app~ticketing.js"></script>
    <script src="/build/vendors~app.js"></script>
    <script src="/build/app~ticketing.js"></script>
    <script src="/build/app.js"></script>

    <!-- ticketing: -->    
    <script src="/build/vendors~ticketing.js"></script>
    <script src="/build/ticketing.js"></script>

```

Which is how the official Webpack Encore resolver works (I guess). Let me know! Thank you!

**Comment by bpolaszek** [comment]
OK, got it.

Can you please run `vendor/bin/phpbf --standard=psr2 -n src/`?
I should move from travis to Github Actions but I don't have the time for that right now.

Thanks,
Ben

**Comment by tonix-tuft** [comment]
> vendor/bin/phpbf --standard=psr2 -n src/

```
$ vendor/bin/phpbf --standard=psr2 -n src/
-bash: vendor/bin/phpbf: No such file or directory
```

Tried to run `composer install` but same error for the missing `phpbf` command.
Did you forget to include this dep in your composer.json?

Also, why didn't you put `vendor` and `composer.lock` in a `.gitignore` file?

Let me know!

**Comment by bpolaszek** [comment]
`vendor/bin/phpcbf` sorry for the typo :-) 

Regarding `.gitignore`, forgot to add them, feel free to do so in a separate PR 🙂

**Comment by tonix-tuft** [comment]
I have run the command, but still there travis check is not passed.

**Comment by bpolaszek** [comment]
Hey there,

I just dropped support for Travis in favor of Github Actions. Can you please rebase on master?

**Comment by tonix-tuft** [comment]
> Hey there,
> 
> I just dropped support for Travis in favor of Github Actions. Can you please rebase on master?

You want me to send you a PR directly on the master branch? Why not merging this branch? Let me know!

**Comment by bpolaszek** [comment]
No, just rebase your PR on `master` and force-push: new CI will be triggered.

**Pull request closed without merging**
